version: '3.8'
services:
  php-web:
    image: ilunne/php7.4-mysqli
    container_name: homepage-php
    networks:
      - app-network
    ports:
      - "8080:80"
    volumes:
      - /root/homepage:/var/www/html
    environment:
      - TZ=America/Recife
      - PHP_DATE_TIMEZONE=America/Recife
      - APP_MASTER_KEY=Dinov@tech123
      - APP_MODE_VET=false
      - DB_HOSTNAME=10.0.0.208
      - DB_DATABASE=app_multas
      - DB_USERNAME=azakdb
      - DB_PASSWORD=Dinov@tech123
      - DB_CHARSET=UTF8
      - PYTHON_API_URL=http://app:5000
    restart: always

networks:
  app-network:
    external: true 